### ISSUE TITLE
Do I need a replica in every backup region?

### ISSUE THREAD

**Issue by danielzfranklin** [superfly/fly_postgres_elixir#11]
When fly deploys my app to a backup region I get a connection error because I only have databases for every region in the non-backup region pool.

It seems to me this library could either have a mapping of "nearby" regions and fallback to a nearby database if there isn't a replica in the exact region, or take control of creating replicas itself.

Is there something obvious I'm missing that makes this not a big deal?

**Comment by brainlid** [comment]
@danielzfranklin good question! Yes, there are two ways to solve this.

One is on your side. You can turn-off backup regions where you don't have a database.

Run this command to see your current backup list:

```
fly regions backup list
```

It lists the regions that your application will use as a backup region if there is problem getting into your top picks. As you noticed, you probably don’t have your database running in that backup region!

You can turn off the backup regions. So for me, if my app is deployed to `lax` and `syd`, I’ll set the backup regions like this…

```
fly regions backup lax syd
```

Then it shows as no _other_ backup regions. 

The second fix is a recent internal change made at Fly that this library doesn't yet take advantage of. It's a way to use DNS to find a closest one.

I need to make the second fix anyway, but you can also use the first fix as a way to control your regions more.

**Comment by brainlid** [comment]
@danielzfranklin I released v0.1.13. Internally it uses a new Fly.io DNS feature that lets it find the "nearest" replica. This should fix issues when a replica instance is temporarily deployed to a backup region. However, this will still have an issue if your "primary" instance is deployed to a backup region because it will think it's now acting as a replica and there won't be any primary instances to perform the DB changes. 

For this reason, you may still want to disable the backup regions for your app.

Hope this helps!
