### ISSUE TITLE
Configure timeout for RPC calls

### ISSUE THREAD

**Issue by fedeotaran** [superfly/fly_postgres_elixir#7]
Hi @brainlid! 😄 
I continue play with the lib. I have some timeout errors on some queries:

```
19:45:50.563 [error] RPC notification timeout calling Elixir.Brandkit.Repo.Local.insert/2}
19:45:50.566 [debug] QUERY OK db=2.4ms
rollback []
19:45:50.567 [error] GenServer #PID<0.3459.0> terminating
** (stop) time out
    (fly_postgres 0.1.11) lib/fly_postgres.ex:136: Fly.Postgres.rpc_and_wait/4
    ...
```

It might be a good idea to be able to increase the timeout from a configuration for methods:
https://github.com/superfly/fly_postgres_elixir/blob/1e08753fad2ec9c71b992d951f1b2a517f15177c/lib/lsn/lsn_tracker.ex#L95
or
https://github.com/superfly/fly_postgres_elixir/blob/1e08753fad2ec9c71b992d951f1b2a517f15177c/lib/lsn/lsn_tracker.ex#L77

What do you think?

**Comment by brainlid** [comment]
I agree that a more centralized config for the timeout would be handy. Especially since some of the calls are used deeper in other calls.

If the timeout is failing after 5 seconds, there may be a better approach. 

For instance:

- Instead of performing multiple insert/update calls, RPC to the primary region using `Fly.Postgres.rpc_and_wait(MyModule, :do_complex_work, [arg1, arg2])`
- If the function `do_complex_work` just takes a lot of time to do the work, we probably don't want to block and wait for execution to finish. It might be better to submit a job and use PubSub to be notified when the work is done.

There could be other issues happening too. I can't tell from. But yes, a better timeout config would be good. Either let a per-call config pass through from other callers or allow setting a different system-wide default value.

**Comment by brainlid** [comment]
I reworked the way timeouts work. Timeouts are now passed through as named options using a Keyword list.

Note that 2 different timeouts can be specified.

- `:rpc_timeout` - The duration to allow for the RPC function to execute before timing out. Default is 5 seconds.
- `:replication_timeout` - The duration to allow for the tracked LSN value to replicated to the local replica before timing out. Default is 5 seconds.

These changes may not entirely address your issues. Feel free to open a new ticket if there are additional ways it can be improved. Thanks!

**Comment by fedeotaran** [comment]
Sorry for answering so late!

Finally we improve the code to have shorter transactions. But I think it's a good feature!

The lib is amazing. We haven't had any major problems so far.

I will keep it updated to be able to use these features.

Thanks! @brainlid 😃

**Comment by benonymus** [comment]
Hey @brainlid,

I just found this issue due to a similar timeout message.
In my case it looks like it is coming from the `:replication_timeout` bit.

```
[error] LSN RPC notification timeout calling Elixir.XXXX.Repo.Local.update/2}
```

Is that normal for the replication to take more than 5 seconds?

We are deployed on Fly with the main db instance being in Singapore and the replica in Chicago (quite far).
 
While in some cases we might be ok with not waiting for the replication, I am not sure if that is true for every case.
