### ISSUE TITLE
Tightly bound to Fly.io?

### ISSUE THREAD

**Issue by wadestuart** [superfly/fly_postgres_elixir#9]
Hello,  this looks like a great lib! I have been looking at it and it seems like a pretty elegant solution to multiread/write over high latency deployments.   I do understand why its currently tightly integrated to fly_rpc,  but I am wondering if there is any appetite to mutate this module into a more general solution that is configurable where fly.io dependency is just one of the backends/configurations possible? 

For instance a backend being created for onprem where the write head and locals can be configured and maybe failover via config, and a aws or other PAASs?   

I think this could be a more general solution to this type of problem,  but as it stands its very bound to fly (don't get me wrong I really like Fly.io but for various reasons it may not be a usable environment for certain projects).  Totally understand if there is resistance for this -- I just like this design and it seems like it could be a much more general solution in the toolbox (to the end that I am thinking about reimplementing a similar idea with pluggable backends).

**Comment by brainlid** [comment]
Hey @wadestuart! I'm open to ideas you have for how to make it more general. I'd love to hear your ideas on how to do that. Mainly because I can't think of how to do it. Say I wanted to do it in an AWS single region to use read replicas there on some of the server instances. I'm not sure how it could be nicely segregated to identify that one should be a replica and another be primary when all the instances are from the same Docker image.

I'd love to hear any ideas you have on how to generalize the way to partition the instances. In Fly, it works naturally with regions.

**Comment by brainlid** [comment]
I'm open to talking about how this could be more generic! For now I'm closing it.

**Comment by Kloenk** [comment]
My Idea to do this would be a generic dispatcher which can be set in the using opts. So the default one is fly. But if for example I'm running my own psg cluster, I can write my own dispatcher module which is bound to my use case.
